### ISSUE TITLE
Multiple Jodi's

### ISSUE THREAD

**Issue by intivalderas** [Denperidge/osoc-interlink#1]
As jodi-deloof and jodi-de-loof

https://denperidge.github.io/osoc-interlink/?participant=jodi-de-loof
https://denperidge.github.io/osoc-interlink/?participant=jodi-deloof

**Comment by Denperidge** [comment]
Thank you, great catch! Fixed in https://github.com/Denperidge/osoc-interlink/commit/bcb3f96909e3785c8064737b66a3562d2965d163
